jhu-library-applications/catalyst-blacklight

Gemfile
Gemfile.lock

This isn't needed if you have `node` installed and
the v8 dep takes a large amount of time to compile.
Just make sure to `brew install node` before running the
tests.
If this is merged I'll go and update the HOWTO to include
installing node as well.

Remove mini_racer dependency

---

Gemfile
Gemfile.lock
config/environments/production.rb

The [ExceptionNotification gem](https://github.com/smartinez87/exception_notification) helps capture and email error messages from any Rails application.
It's been extremely helpful for the [B1G/BTAA Geoportal project](https://github.com/BTAA-Geospatial-Data-Project/geoportal). It's particularly helpful to see any 500 errors an application produces.
However, here in Catalyst, ActionMailer appears to be missing several configuration options, so I'm not certain this will work without additional action_mailer config settings. See [BTAA config](https://github.com/BTAA-Geospatial-Data-Project/geoportal/blob/develop/config/environments/production.rb#L66-L76) for example.
UPDATE: Added sendmail default settings in second commit here.

Gems: Add ExceptionNotification for catching and emailing application errors.

---

.github/workflows/ci.yml
env-example
test/controllers/catalog_controller_test.rb
test/controllers/requests_controller_test.rb
test/controllers/users_controller_test.rb
test/system/catalog_test.rb
test/test_helper.rb

Sets an env var ENV['HORIZON_UNAVAILABLE'] to check skipping or performing horizon dependent tests.

Tests: skip horizon dependent tests, if horizon is unavailable

---

.github/workflows/ci.yml
env-example
test/controllers/catalog_controller_test.rb
test/controllers/requests_controller_test.rb
test/controllers/users_controller_test.rb
test/system/catalog_test.rb
test/test_helper.rb

Sets an env var ENV['HORIZON_UNAVAILABLE'] to check skipping or performing horizon dependent tests.

Tests: skip horizon tests if horizon is unavailable (#7)

---

config/environments/production.rb

Blacklight raises a custom error Blacklight::Exceptions::RecordNotFound on items not found. This commit makes sure ExceptionNotification ignores these errors and will pass them through as proper 404s.
Fixes #11

ExceptionNotification: ignore Blacklight::Exceptions::RecordNotFound

---

app/controllers/application_controller.rb
app/controllers/errors_controller.rb
app/views/errors/internal_server_error.html.erb
app/views/errors/not_found.html.erb
app/views/layouts/blacklight/base.html.erb
config/application.rb
config/routes.rb
test/controllers/errors_controller_test.rb
test/controllers/users_controller_test.rb

Removes old JHU exception handling code from application_controller. Moves exception handling to routing and errors_controller with corresponding, customizable views.

Exception Handling: custom 404 and 500 pages

---

app/assets/javascripts/blacklight/blacklight.js
app/views/articles/_search_form.html.erb

WIP
Adds polyfills and a babel-fied version of blacklight.js locally to support IE11. Also closes an svg path element. Not certain this covers all the ills, but is a good start.
Would definitely want to remove this local override when migrating to webpacker and proper transpiling.

IE11 Support

---

app/controllers/reserves_controller.rb

Fixes bug where '@course' isn't found, redirects to 404 page.
One last PR. Thanks again!

Bug fix: rescue to 404 for reserves course not found

---

.github/workflows/ci.yml

This changes the way solr is ran in CI. It doesn't use solr_wrapper, but a solr container that we store at ghcr.io.
This will help speed up getting solr running and we won't be relying on the apache.org servers.

Use docker container for solr

---

Gemfile
Gemfile.lock
config/initializers/rollbar.rb

This installs Rollbar for error monitoring.
This requires the ROLLBAR_ACCESS_TOKEN env variable
to be set on the server. This catalyst-ansible PR sets the env variables up: https://github.com/jhu-library-applications/catalyst-ansible/pull/60/files

Rollbar setup for server-side errors

---

.github/workflows/release.yml

This sets up a workflow that is triggered when a release is published. Right now it only notifies 
a slack channel.

Add a GitHub Actions workflow for releases

---

app/javascript/umlaut_include.js

The test are currently failing unrelated to this change, but rather due to Umlaut timeouts.

Added check to ensure existence of #hathi-etas element before comparison

---

app/controllers/catalog_controller.rb

Example error:
[Catalyst Error] (2 times)catalog index (ActionView::Template::Error) "undefined method `strip' for [\"Book\"]:Array"

Fix old format facet errors

---

config/deploy.rb

We use the web role in our cap scripts not the default app role used by capistrano-passenger.

Passenger restart for web role

---

Gemfile
Gemfile.lock

This updates our Rails installation to Rails 5.2.4.5 to bring
in a patch for this CVE: https://github.com/advisories/GHSA-8hc4-xxm3-5ppp
The CVE only applies to installs that use postgresql so it does
not apply to this app.

LAG-4045 Update for CVE

---

app/helpers/search_helper.rb
app/views/catalog/_search_form.html.erb
test/system/advanced_search_link_test.rb

This changes the URL to advanced search so that it doesn't
include the current params. Without this the data in Google Analytics
contains those params and makes analysis harder.

LAG-4048 Always use simple url for advanced search

---

config/environments/development.rb

This is required for local ansible deployments. This
gem is no longer installed with catalyst.

Remove Bullet refs from development.rb

---

app/controllers/catalog_controller.rb

Blacklight has a config called `crawler_detector` that
can be used to turn off saved searches and based on the
user agent.
This sets the detector to look for `bot` in the user agent.

LAG-3997 Turn off saved searches for bots

---

app/helpers/search_helper.rb
test/system/advanced_search_link_test.rb
test/system/catalog_test.rb
test/system/search_test.rb

This simplifies the creation of the advanced search link
based on changes from LAG-4050. This avoids a 
search term always being in the `Any Field` field
in advanced search even if you selected title from 
the dropdown. 
This overrides the default blacklight label behavior
so that we show the Any Field label on results pages
for the quick search/default search.

LAG-4068 LAG-4069 Advanced search/quick search behavior

---

app/controllers/reserves_controller.rb

Removed existing rescue which throws a routing exception which is currently being sent to bug trackers.
This change will catch the ActiveRecord::RecordNotFound exception on the Reserves Controller and respond with a 404 status and render the appropriate template.

Remove ActionController::RoutingError exceptions thrown by missing reserves 

---

Capfile
Gemfile
Gemfile.lock
config/deploy.rb
config/schedule.rb
lib/tasks/nightly_cleanup.rake

This adds a nightly task using `whenever` to
clear out saved searches.The cron tab
entries are installed on the server when the
application is deployed with `capistrano`.
It looks like tasks and the capistrano/whenever
setup existed before, but weren't migrated when
the move to `ansible` happened.
I removed the existing tasks for cleaning out searches
and users. As we accumulate users we will need to
reinstate a similar task, but we will need to be careful
because we won't be able to use `TRUNCATE` like we are
with searches.

LAG-3997 Catalyst stored searches

---

app/views/catalog/_citation.html.erb

This change should sort the entry for each style alphabetically. I added three sorts because each style could display the authors' name differently.

LAG 4114 Adds an alphabetical sort for each citation style

---

app/javascript/packs/application.js.erb
package.json
yarn.lock

This removes AppSignal JS. We are relying
on Sentry.io for capturing front-end errors.

Remove AppSignal JS

---

app/controllers/catalog_controller.rb
app/helpers/cql_helper.rb
test/helpers/cql_helper_test.rb
test/system/cql_test.rb

Find It makes links to Catalyst that look like this:
```
/catalog.html?content_format=marc&f%5Bformat%5D%5B%5D=Journal%2FNewspaper&q=title+%3D+"%5C"Accounts+of+Chemical+Research%5C""&search_field=cql
```
This PR redirects those URLs to this path:
```
/catalog?q=Accounts+of+Chemical+Research&search_field=all_fields
```
This will keep the user from being in a state where they are searching with CQL.

LAG-4185 Redirect CQL queries from Find It

---

Gemfile.lock

It looks like the Gemfile.lock specified to use macOS for Nokogiri at some point. This adds the additional Linux platform that we need for CI and prod.

Add x86_64 to Gemfile.lock

---

Gemfile
Gemfile.lock
app/controllers/catalog_controller.rb
app/views/catalog/_index_marc.html.erb
app/views/catalog/_microformat_default.html.erb
app/views/catalog/_show_main_content.html.erb
test/system/detail_page_test.rb
test/system/search_test.rb

unAPI can now be used by Zotero, the RefWork bookmarklet and other citation mangers to capture item metadata for both individual and bulk export (search results and bookmark pages).
https://github.com/cul-it/blacklight-unapi

LAG-4268 Added Blacklight unAPI gem to replace COinS data

---

.github/workflows/ci.yml

This adds the coverage report from SimpleCov to
the GitHub Actions CI workflow.
The results can be accessed on the page for the CI run in the Artifacts section:
When you download the artifact it will be a zipped folder with HTML.

Upload SimpleCov coverage

---

app/helpers/application_helper.rb
app/views/application/_borrow_direct.html.erb
app/views/catalog/_show_marc.html.erb
test/helpers/application_helper_test.rb

This adds a helper that checks the format of the Solr document being
displayed. If it has the 'Map/Globe' format it won't display FindIt URLs
or load the FindIt JS on the item page.
FindIt was sending maps to SFX as books. We don't have map coverage in SFX
so this ensures we don't look anyway.

LAGSCRUM-196 Unrelated "Online Access" link appearing in map records

---

config/deploy.rb

This adds the `tmp/cache` folder to capistrano's shared folders
this will avoid creating a new cache when deploying.

LAG-4727 Test back button behavior on Catalyst detail record

---

app/javascript/load_online_access.js
package.json
yarn.lock

This addition fixes this IE11 bug: https://sentry.io/organizations/johns-hopkins-library-applicat/issues/2918084170/?project=5634978

Add a polyfill for IntersectionObserver, which isn't present in IE11

---

app/views/requests/_head_notes.html.erb

This `item_display` can sometimes be
`nil` and triggers an unhelpful `Exception`.

HELP-27722 User experiencing problems requesting

---

app/presenters/sfx_service_presenter.rb
app/views/online_access/_url.html.erb
app/views/online_access/show.html.erb
test/presenters/sfx_service_presenter_test.rb

This adds the SFX service type to the display of Online Access
links.

LAGSCRUM-533 Make Catalyst online links from SFX match SFX display

---

docker-compose.yml

This adds the horizon-holding-info-servlet to do the `docker-compose`
file. It's preconfigured to work with horizon stage.

Add Horizon holding info servlet to docker-compose

---

.docker/catalyst/Dockerfile
app/controllers/catalog_controller.rb
app/lib/subject_overrider.rb
app/lib/subject_overrider_terms.rb
config/translation_maps/subject_overrides.yml
marc_display/app/helpers/marc_display_logic.rb
marc_display/app/models/marc_display/link.rb
marc_display/app/views/marc_display/_marc_line.html.erb
test/lib/subject_overrider_terms_test.rb
test/lib/subject_overrider_test.rb

This adds a class called `SubjectOverrider` that's used
for overriding subjects based on the translation
map present in `config/translation_maps/subject_overrides.yml`.
A yaml file that has the same name should also be edited in the `catalyst_traject`
repo when making changes to the map.
Catalyst doesn't display values directly from Solr. It displays
content from a binary MARC record stored in Solr. This class
is used to translate the subjects that are displayed from that
record.

LAGSCRUM-548 Implement workflow to overlay subject headings in Catalyst

---

app/controllers/borrow_direct_controller.rb

This changes the ID used in the BorrowDirect URL so that it uses the hopkins_id and not the barcode. This is happening because of an NCIP server upgrade.

Replace barcode with hopkins ID in BD URL
